name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup mise
      uses: jdx/mise-action@v2
    - name: Get pnpm version
      id: mise
      run: |
        echo "node_version=$(mise current node)" >> "$GITHUB_OUTPUT"
        echo "pnpm_version=$(mise current pnpm)" >> "$GITHUB_OUTPUT"
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Install, build, and upload
      uses: withastro/action@v3
      with:
        node-version: ${{ steps.mise.outputs.node_version }}
        package-manager: pnpm@${{ steps.mise.outputs.pnpm_version }}
      env:
        URL: ${{ steps.pages.outputs.origin }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
